apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-server
  template:
    metadata:
      labels:
        app: image-server
    spec:
      containers:
        - name: image-server
          image: ghcr.io/devinsightforge/image-server:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongo_connection_uri"

---
apiVersion: v1
kind: Service
metadata:
  name: image-server-service
spec:
  type: NodePort
  selector:
    app: image-server
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4000
      nodePort: 30001
